# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aOnMFaCnAvtuWXe5YtVYghHkho_hN4v
"""

import pandas as pd
import re
import os

def process_form5500(file_path):
    # 1. read file
    print(f"Reading: {file_path}")
    try:
        # try to read two code formats
        df = pd.read_csv(file_path, encoding='utf-8', low_memory=False)
    except:
        df = pd.read_csv(file_path, encoding='latin1', low_memory=False)

    # 2. search column 'PLAN_NAME'
    col_name = 'PLAN_NAME'

    if col_name not in df.columns:
        print(f"Error: Could not find the column named '{col_name}'.")
        print("Please check your CSV file. The current column names are：", df.columns.tolist())
        return

    print(f"The target column has been locked: {col_name}")

    # 3. matching for 401(k) and 403(b)
    pattern = r'401\(k\)|403\(b\)'
    filtered_df = df[df[col_name].str.contains(pattern, case=False, na=False, regex=True)]

    # 4. Extract the duplicate-free list
    unique_plans = filtered_df[col_name].unique()
    result_df = pd.DataFrame(unique_plans, columns=['Full_Plan_Name'])

    # 5. Save the result
    output_file = "filtered_401k_403b_plans.csv"
    result_df.to_csv(output_file, index=False)
    print(f"Processing completed! {len(unique_plans)} plans have been selected.")
    print(f"The result has been saved to: {output_file}")

# --- colab other ---
try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if __name__ == "__main__":
    if IN_COLAB:
        print("Detected Colab environment. Please upload the file ...")
        uploaded = files.upload()
        if uploaded:
            fname = list(uploaded.keys())[0]
            process_form5500(fname)
            files.download("filtered_401k_403b_plans.csv")
    else:
        path = input("Please enter the path: ")
        if os.path.exists(path):
            process_form5500(path)
        else:
            print("The file path does not exist!")